server {
    listen 80;

    # 1. 리액트 정적 파일 서빙
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. 백엔드 API 프록시 설정
    # 프론트엔드에서 /api/hello로 요청을 보내면 8000번 포트의 백엔드로 전달합니다.
    location /api {
        proxy_pass http://13.125.226.36:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}